### ISSUE TITLE
No way to log in inside devenv

### ISSUE THREAD

**Issue by RDIL** [cirruslabs/cirrus-ci-web#101]
![Screenshot 2019-08-06 at 11 24 05 AM](https://user-images.githubusercontent.com/34555510/62553112-c853e280-b83c-11e9-9b44-da2e845fba67.png)
clicking brings you to the hosted version

**Comment by fkorotkov** [comment]
Clicking what?

**Comment by RDIL** [comment]
Sign in

**Comment by fkorotkov** [comment]
That's expected. In order to run it locally you simply need to remove Same Site restrictions on `cirrusUserId` and `cirrusAuthToken` cookies for api.cirrus-ci.com.

<img width="551" alt="Screen Shot 2019-08-06 at 8 30 32 AM" src="https://user-images.githubusercontent.com/989066/62553622-8323b680-b824-11e9-99a5-4a76a368c86c.png">
