### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-web#173]
Let's get fancy and create a dark themer. It will require dynamic [`cirrusTheme.ts`](https://github.com/cirruslabs/cirrus-ci-web/blob/master/src/cirrusTheme.ts). Probably removing constants like `cirrusWhite`, etc.

**Comment by RDIL** [comment]
I can try to do this later today

**Comment by fkorotkov** [comment]
Docs for reference: https://material-ui.com/customization/palette/#dark-mode

**Comment by RDIL** [comment]
Here is what I got so far
![Screenshot 2020-05-08 at 4 49 47 PM](https://user-images.githubusercontent.com/34555510/81448177-f78cdc80-914b-11ea-8ea4-5200b4490cc9.png)

**Comment by RDIL** [comment]
Why is this help wanted?  I opened #175

**Comment by fkorotkov** [comment]
Just labeling issues. #175 is still WIP and seems help can be appreciated there. 👌

**Comment by squidfunk** [comment]
__Estimate: 8.0-12.0h__

As you already noted, @fedor, this could be built off the MUI dark mode. We could take what @RDIL already built and adapt the theme to use the provided colors. It's hard to put an estimate on it, because the work here definitely lies in the details, but I think we should have something reasonable within a day or two. I'd first stick to their color palette, as I'd assume it's already pretty tweaked and go from there.

**Comment by AlexWayfer** [comment]
Just a ping after almost year: I want it!

**Comment by fkorotkov** [comment]
@AlexWayfer your wish was granted!

**Comment by AlexWayfer** [comment]
> @AlexWayfer your wish was granted!

Wow! I guess it's the first time when ping (bump) worked, and almost immediately! 😅
