### ISSUE TITLE
Active Repositories should show forks

### ISSUE THREAD

**Issue by fkorotkov** [cirruslabs/cirrus-ci-web#22]
At the moment Active Repositories shows latest master build for active repositories. Frequently people are working in non-master branch in forks, therefore there is no master build for a fork.

**Comment by DanTup** [comment]
Also, when adding Cirrus to a new project, you'll probably (hopefully?) add it on a fork while you configure the config file, so having it not show up is a bit confusing.

**Comment by fkorotkov** [comment]
@DanTup unfortunately most of the users just add Cirrus to all repositories, that's why there is a lazy initialization until `.cirrus.yml` is pushed.

**Comment by DanTup** [comment]
Sorry I meant branches, not fork/repo. If you want to enable Cirrus for an existing project, you'll probably start by adding a `.cirrus.yml` file on a branch and push it, so you can make sure everything works before you put it in master (otherwise you might get red status badges while working on it). But when you push to the branch, it won't show up in active repos, so you might wonder whether it's actually building your branch or not if you come directly to Cirrus.

**Comment by fkorotkov** [comment]
Oh. You need to change `CIRRUS_SHELL`. By default `sh` is used and you need bash.

Actually let me add a check to see if bash installed and use `bash` if possible.

**Comment by DanTup** [comment]
Wrong issue (https://github.com/cirruslabs/cirrus-ci-docs/issues/28), but thanks :) I'll add it to test, but LMK if you change the default and I'll remove.

**Comment by fkorotkov** [comment]
It got implemented at some point.
