### ISSUE TITLE
Logs don't show (/stream) until task completes

### ISSUE THREAD

**Issue by DanTup** [cirruslabs/cirrus-ci-web#25]
I don't know if this may be related to the changes to handle the strange timeouts that were seen, but since yesterday evening (at least) it seems that logs don't appear until a step finishes now, they just look like this:

![screen shot 2018-08-23 at 8 21 54 am](https://user-images.githubusercontent.com/1078012/44510843-ab66e380-a6ad-11e8-9d91-6ac977e4f20a.png)

The commands being run in this step are fairly simple:

```
    iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
    choco install -y ruby
    choco install -y nodejs.install
    refreshenv
```

Though I see it in the others (such as those running flutter commands). The output does appear once the step completes (if I reload the page).

**Comment by fkorotkov** [comment]
It can happen sometimes but it shouldn't be frequently. Cirrus CI Agent is trying to stream logs as they come but if there were network issues it stops and only re-uploads the whole log after completion.

Seems it happens frequently since you are noticing. Do you happen to have ids of tasks where you saw it?

**Comment by fkorotkov** [comment]
This should be fixed now + logs will be streamed with less delay. 😅Sorry about the inconvenience.
