### ISSUE TITLE
Terminal (in rerun) hangs after several seconds

### ISSUE THREAD

**Issue by edsantiago** [cirruslabs/cirrus-ci-web#538]
Re-ran a failed task, using the "in terminal" option. Terminal comes up but does not accept any input (maybe because `setup` task is running, instead of `main`?)

Once `main` task starts, terminal clears, redisplays prompt. It accepts input, but only for a few seconds, then stops accepting input. Cursor is still solid block; moving pointer to different window and giving it focus, then cursor becomes outline.

None of the usual X11 paste mechanisms work. ^C either. Terminal is, for all purposes, hung. 

Going to the /task/NNN URL on a different computer, I get a few seconds of being able to type, then it hangs similarly. Browser is firefox-111 on Gentoo and on Fedora 37.

**Comment by greysummer412** [comment]
Hi there, it seems like you're experiencing some issues with running a failed task using the "in terminal" option. It sounds like the terminal is not accepting any input, possibly due to the setup task running instead of the main task. Once the main task starts, the terminal clears and redisplays [Go To](https://www.gotohomestay.com/) the prompt, but only accepts input for a few seconds before hanging. Additionally, the cursor is a solid block and only becomes an outline when moving the pointer to a different window and giving it focus. It's unfortunate that none of the usual X11 paste mechanisms work, and even ^C does not work. It seems like the terminal is hung and unresponsive. Perhaps you could try accessing the /task/NNN URL on a different computer to see if that resolves the issue, but it sounds like a larger problem.

**Comment by Sakura286** [comment]
I have the same question. Browser is Edge 111 and Chromium 102 on Windows 11 22H2.

**Comment by edsantiago** [comment]
Working fine today. Terminal session is still live, 15 minutes after starting, including some 30-second idle times. Thank you!
