### ISSUE TITLE
convert to typescript

### ISSUE THREAD

**Issue by geekflyer** [cirruslabs/cirrus-ci-web#73]
Hi,

after having a frustrating experience with many CI/CD systems I feel like cirrus ci might be the middle ground I'm looking for, at least backend functionality-wise.
However I feel like the UI / UX leaves a lot to be desired and I also think the UI is quite confusing at times.
I understand you are a small team or just one person company? and you have to prioritize accordingly and perhaps the focus is currently more on backend stuff.
I honestly thought a bit that I could just build a custom UI for cirrus for internal use in my company but positively realized that your UI is OSS.
So that brings me to that idea: Maybe I should contribute a bit. I have quite some experience with React, graphql etc. but I'm kinda opionated about using TypeScript for almost everything these days, especially for side projects:-). Therefore I'd like to ask if you're open to a PR which converts this project to TypeScript. In the context of this project I think it also makes OSS contributions easier because the codebase is easier to understand / navigate. Yeah I could give you a huge list of TypeScript is saving the world, but I'd rather leave that to other folks and their Medium posts ;-)

So: Would you be open to an PR which turns this into TypeScript?

**Comment by fkorotkov** [comment]
I personally thought about it but did not investigate enough how Typescript will interact with Relay. I'm very glad that Relay takes away the heavy lifting of managing stores and propagating object updates. 

Seems since the last time I checked this happened: https://github.com/relay-tools/relay-compiler-language-typescript So I'm totally up for migrating to TypeScript! I personally a big fan of languages with proper compilers. 😅

**Comment by geekflyer** [comment]
ok cool. I spend some time on this and made some good progress. There is still a bunch of type errors I need to resolve but expect a PR in the next 1-2 weeks.

**Comment by fkorotkov** [comment]
Wow! Glad to hear! 🙌
